name: 'create-asana-task'
description: 'Creates an Asana task for the current commit'
author: 'Gabs <gabs@invoicesimple.com>'
inputs:
  access_token:
    required: true
    description: 'Asana access token'
  workspace_id:
    required: true
    description: 'Asana Workspace ID'
  project_id:
    required: true
    description: 'Asana Project ID'
runs:
  using: 'node16'
  main: 'dist/index.js'
